name: CI

on: [ push, pull_request ]

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
            toolchain: linux-gcc

          - os: macos-latest
            compiler: clang
            toolchain: macos-clang

          - os: windows-latest
            compiler: msvc
            toolchain: windows-msvc

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SetUp MySQL
        uses: ankane/setup-mysql@v1
        with: 
          mysql-version: 8.0
          database: test_ormppdb

      - name: Verify MySQL Connections
        run:  mysql -uroot -e'show databases;'

      - name: Configure CMake
        run:  cmake -B${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build with ${{ matrix.compiler }}
        run:  cmake --build ${{github.workspace}}/build --config Release

      - name: Test
        working-directory: ${{github.workspace}}/build
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: ctest -C Release