name: Upload CodeCov Report

on: [ push, pull_request ]

jobs:
  run:

    runs-on: windows-latest
    name: Upload Code Coverage Report

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: ‘2’
        id: checkout_code

      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        id: setup_msbuild

      - name: Run MSBuild
        id: run_msbuild
        run: msbuild /p:Configuration=Debug /p:Platform=x86 ormpp.sln

      - name: Setup VSTest and add to PATH
        uses: darenm/Setup-VSTest@v1
        id: setup_vstest

      - name: Setup OpenCppCoverage and add to PATH
        id: setup_opencppcoverage
        run: |
          choco install OpenCppCoverage -y
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

      - name: Generate Report
        id: generate_test_report
        shell: cmd
        run: OpenCppCoverage.exe --sources .. --export_type cobertura:ormppCov.xml -- "vstest.test_ormpp.exe"

      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./ormppCov.xml
          fail_ci_if_error: true
          functionalities: fix