name: Upload CodeCov Report

on: [ push, pull_request ]

jobs:
  run:

    runs-on: windows-latest
    name: Upload Code Coverage Report

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: ‘2’
        id: checkout_code

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.0
        with:
          arch: amd64

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -G Ninja -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Setup OpenCppCoverage and add to PATH
        id: setup_opencppcoverage
        run: |
          choco install OpenCppCoverage -y
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

      - name: Generate Report
        id: generate_test_report
        shell: cmd
        run: OpenCppCoverage.exe --sources ${{github.workspace}} --export_type cobertura:ormppCov.xml -- "${{github.workspace}}/build/tests/test_ormpp.exe"

      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./ormppCov.xml
          fail_ci_if_error: true
          functionalities: fix