name: Ubuntu 20.04 (clang)

on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]

jobs:
  build_by_clang:
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        mode: [ Debug, Release ]
        libcxx: [ OFF ]
        ssl: [ ON, OFF ]
        
    services:
      mysql:
        image: "mysql:8.0"

        options: >-
          --health-cmd "mysqladmin ping --silent"
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
          -e MYSQL_DATABASE=test_ormppdb

        ports:
          - "3306:3306"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure CMake
        run: CXX=clang++ CC=clang cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.mode}} -DBUILD_WITH_LIBCXX=${{matrix.libcxx}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.mode}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.mode}} -j `nproc` -V
