name: Ubuntu 20.04 (clang)

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build_by_clang:
    strategy:
      matrix:
        mode: [Release]
        libcxx: [OFF]
        ssl: [OFF]
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure CMake
        run: CXX=clang++ CC=clang cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.mode}} -DBUILD_WITH_LIBCXX=${{matrix.libcxx}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.mode}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.mode}} -j `nproc` -V
