name: Ubuntu 20.04 (gcc)

on:
  push:
    branches:
      - master
      
  pull_request:
    branches:
      - master
      
jobs:
  build_by_gcc:
    runs-on: ubuntu-20.04
  
    strategy:
      matrix:
        mode: [Debug, Release]
        ssl: [ON, OFF]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure CMake
        run: CXX=g++ CC=gcc cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.mode}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.mode}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.mode}} -j `nproc` -V
