name: macOS Monterey 12

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build_on_mac:
    runs-on: macOS-12

    strategy:
      matrix:
        mode: [Debug, Release]
        ssl: [ON, OFF]

    services:
      mysql:
        image: "mysql:8.0"

        options: >-
          --health-cmd "mysqladmin ping --silent"
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
          -e MYSQL_DATABASE=test_ormppdb

        ports:
          - "3306:3306"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: SetUp HomeBrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        
      - name: Install MySQL
        run: brew install mysql

      - name: Configure CMake
        run: CXX=clang++ CC=clang cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.mode}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.mode}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.mode}} -j `nproc` -V
