name: macOS Monterey 12

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build_on_mac:
    runs-on: macOS-latest
  
    strategy:
      matrix:
        mode: [Release]
        ssl: [OFF]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: SetUp HomeBrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        
      - name: Run MySQL Docker container
        run: |
          docker run -d -p 3306:3306 --name mysql \
            -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            mysql:latest

      - name: Verify MySQL installation
        run: mysql --version

      - name: Configure CMake
        run: CXX=clang++ CC=clang cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.mode}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.mode}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.mode}} -j `nproc` -V
