name: Windows Server 2019

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_on_windows:
    runs-on: windows-2019

    strategy:
      matrix:
        mode: [ Debug ] #[ Release, Debug ]
        arch: [ amd64 ] #[ amd64,x86 ]
        ssl: [ OFF ] #[ ON, OFF ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.0
        with:
          arch: ${{ matrix.arch }}

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DENABLE_SSL=${{matrix.ssl}} -DCMAKE_CXX_FLAGS="-DMDd" -G Ninja -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.mode }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.mode}} -j 1 -V
