name: Windows Server 2022

on: [ push ]

jobs:
  build_on_windows:
    runs-on: windows-2022

    strategy:
      matrix:
        mode: [ Release ]
        arch: [ amd64 ]
        ssl: [ OFF ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SetUp MySQL
        uses: ankane/setup-mysql@v1
        with: 
          mysql-version: 8.0
          database: test_ormppdb
        
      - name: Verify MySQL Connections
        run: mysql -uroot -e'show databases;'

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.0
        with:
          arch: ${{ matrix.arch }}

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DENABLE_SSL=${{matrix.ssl}} -G Ninja -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.mode }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.mode}} -j 1 -V
